esphome:
  name: magichome_5ch
  platform: ESP8266
  board: esp8285
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "MagicHome 5CH Fallback Hotspot"
    password: "12345678"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
  - platform: rgbww
    name: "MagicHome 5CH"
    red: red_channel
    green: green_channel
    blue: blue_channel
    cold_white: cw_channel
    warm_white: ww_channel
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K

output:
  - platform: esp8266_pwm
    id: red_channel
    pin: GPIO14
  - platform: esp8266_pwm
    id: green_channel
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue_channel
    pin: GPIO13
  - platform: esp8266_pwm
    id: ww_channel
    pin: GPIO15
  - platform: esp8266_pwm
    id: cw_channel
    pin: GPIO5

